# Generated by Selenium IDE
import pytest
import time
import json
import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from pymongo import MongoClient

client = MongoClient("mongodb+srv://wondercodehome:wondercode@wondercode-k26sv.mongodb.net/admin?retryWrites=true&w=majority")
db = client.whstore
collection = db.currency

class TestUsd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usd(self):
    self.driver.get("https://www.google.com/")
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("usd to cop")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    usd = self.driver.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').text.replace(".","").replace(",",".")
    data = {
      "type": "usd",
      "value": float(usd),
      "timestamp": datetime.datetime.utcnow()
    }
    collection.insert_one(data)
